---
meta:
  name: canary-go
  target: sw-staging
  url: (( vault "secret/pipelines/concourse:staging-url" ))

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner: starkandwayne
    repo: canary-go
    access_token: (( vault "secret/pipelines/canary-go/github:token" ))
    private_key: (( vault "secret/pipelines/canary-go/github:private" ))

  slack:
    channel: "#concourse"
    webhook: (( vault "secret/pipelines/canary-go/slack:webhook" ))
    success_url: '(( concat meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME" ))'

jobs:
- name: shipit
  plan:
    - (( inline ))
    - do:
      - (( merge ))
      - name: inputs
        aggregate:
        - (( merge on get ))
        - get: git
          trigger: true
      on_success:
        put: notify
        params:
          channel:  (( grab meta.slack.channel ))
          username: (( grab meta.slack.username ))
          icon_url: (( grab meta.slack.icon ))
          text:     (( concat meta.slack.success_moji " " meta.pipeline " has succeeded through all steps! (<" meta.slack.success_url "| shipit build $BUILD_NAME>)" ))
